package:
  name: pyaerocom
  version: 0.12.1rc1

source:
  url: https://pypi.io/packages/source/p/pyaerocom/pyaerocom-0.12.1rc1.tar.gz
  sha256: b6b41fe9afffeea7a579b2d881b58f5242d7bd3668caf6144d8aaebfb02fbae7

build:
  number: 0
  entry_points:
    - pya=pyaerocom.scripts.cli:main
  noarch: python
  script: "pip install . --no-deps -vv "

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - iris >=2.1.0, <3.1.0
    - xarray >=0.16.0
    - cartopy >=0.16.0
    - matplotlib >=3.0.1
    - scipy >=1.1.0
    - pandas >=1.3.0
    - seaborn >=0.8.0
    - geonum
    - numpy
    - simplejson
    - requests
    - reverse-geocode
    - tqdm
    - openpyxl

test:
  imports:
    - pyaerocom
  source_files:
    - tests/test_colocation.py
  requires:
    - pytest
    - pytest-dependency
  commands:
    - ls
    - pytest tests/

about:
  home: https://github.com/metno/pyaerocom.git
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Python tools for the AeroCom project
  doc_url: https://pyaerocom.readthedocs.io/en/latest/
  dev_url: https://github.com/metno/pyaerocom

extra:
  recipe-maintainers:
    - avaldebe
    - jgliss
    - jgriesfeller
    - dulte
